from .metis_partition import partition_graph as metis_partition
from .louvain_partition import partition_graph as louvain_partition
from .label_propagation_partition import partition_graph as label_propagation_partition
from .greedy_modularity_partition import partition_graph as greedy_modularity_partition